language: python
python:
- "3.7"
global:
  env:
  - secure: SdXCO9Cnft2+7TJ+fzKc0NqEMNbAX38ClUmvuThWoKoNgMR79LAtzzAMJ7NcCq2EKj9rXe9nzwhKqaXvmGsL2Xs7z3wHLxMs6OTLkrIx6zUOMuA8Ml26nv4s60caRkgRUysschJu9jZfA/X1ZAWiBs7KalgfOBzMwHslfGEvtaAO5fepfGllHE6HZOaGfcCmFxLB61RjEmJmuqbqfBNeAIq5Kid3iucqTAGuIrjIDY0zNU8uB0zRSQJU5jpVZ/YCm6UZeEntUAz9cJNlnik0W6rK4LSAFddFSAvfPn8cAvj031BmRZN4ir7WG0CVCyASFp30ybnVuwf+RGdCD7KfATLK1+OCh1orHda3qE9CA9pe9YTzf0MClmyXN/Md+NNcm7vyU83sJaKO/MCE3GlScPSV7+CWL6ypgMc0OJezutmw9zkmzHUk38nnmzgV0arzX5PU8BptRD2QO8pLioNdbePfMONtR+LCwm7ExZzw7yte/p5ajiuR51yf62aSBY6RG22jnN47vUZb3s2MDwZunXxDxgQUp+2DYe0b9UFn1DJ6s1uEg6DPzY8411XAfm9+5km7WWWP6TvglXuFx4tDggD1YJ5iVr8Id+bydASaHLCVlG3T40yRv82Xm+DzYAPalUIKLLzBFqA6coQxslfSj3iw55tXUvs7PDmfpfyTpzA=
  - secure: hrSgUPW04XJD65qaja7XeefKhohNqLdF5Rwm1TSp7T7SOEF4vwHC43ogcXj8/hat7LPETe5AVsxVAKyBa0qari/W0/A0c08Jzs/xtyHaq6KpnYosIY/gn+jDqs3x7fy+aeWjjo+iqEURXYQKaEfxmGwPQWvO5VKVBgX91sld//Zjl+sulrriCBFzIeEhBN4zQv5W0xGD81zZRxAmxPeR0RFdJAD++LrDoEWRBr8FaY5wHvRMcmBYgm6Am4+d4ZRXNLz5OL7npcEBOSG/HqWx7eVkl/xaMkLwqT0y2dYqOnPlSapE9fPKCNSGmeIY1Pexa0engg+C/9c/n2V3ibYA1QJM/OEb80kgIxUAnmVSVGNS4DVYYxBzfsqHQw80M0K5PirpWifc8aaQ8ZHa3AnyrKEFJtiolEqDr/GN4sCM77eHY45utT7+AxeIwb/hYlnUsyVUtKxFLf5mxn3w6xNE3zjf1t/QeUEXOHwSsYo/b28nfrKCXH6fdqCvSkT7NmFRyp4VBBoiSTCYNoQtW1leTTEUEtm1xcCd3h8nArom4z6/zWPwsICxGELitmHOLABG6RTQPGJhjfQosNwJ3Z13TFtDI1uKwVHDvjtIBKEiwJjkpwAQ24CuaPKuJMndxC6bV5Fiv3x5pwfNxiR2oaR14uDddh3ki8GTw97ZdjgEo3k=
  - AWS_DEFAULT_REGION=us-east-1
sudo: required
before_install:
# the following is taken from https://github.com/pytorch/vision/blob/master/.travis.yml
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment

# install all the frameworks for testing
- conda install pytorch torchvision -c pytorch
- conda install keras
- git clone https://github.com/qbilius/models/ tf-models
- export PYTHONPATH="$PYTHONPATH:$(pwd)/tf-models/research/slim"
install:
- pip install .
before_script:
- pip install pytest
- pip install pytest-timeout
# download imagenet validation now to avoid out-of-memory errors in script
- sudo -H pip install awscli --upgrade --ignore-installed six  # aws dependency issue: https://github.com/aws/aws-cli/issues/1522#issuecomment-159007931
- aws --no-sign-request --region=us-east-1 s3 cp s3://brain-score-models/imagenet2012-val.hdf5 ./imagenet2012.hdf5
- conda list # list installed package versions
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false"];  then CUDA_VISIBLE_DEVICES= MT_MULTITHREAD=0 MT_IMAGENET_PATH=./imagenet2012.hdf5 pytest --ignore=tf-models -m "not memory_intense"; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ];  then CUDA_VISIBLE_DEVICES= MT_MULTITHREAD=0 MT_IMAGENET_PATH=./imagenet2012.hdf5 pytest --ignore=tf-models -m "not memory_intense and not private_access"; fi

notifications:
  slack:
    if: |
      branch = master AND \
      type IN (push, api, cron)
    on_success: change
    on_failure: always
    secure: "eCS+HaOHPMTXTplsowGKt4Ibf19Lwd0ZWkQpbFdW06hgEIJDxjAfrTRSHV73YF8X4mrvQRyZ9Kax0n2OZUW3ulPaavdPVKgnJRoSYAToImIYZoMk5evFy/YHvtpxtuWGnV2NzTtktKLPB3QgwGehZqbMVuBE7HVsYpaqJwI8n82X6Gwcr+k9RI4A96Zi8HESPAJO/TTjrCxeYNM8jve/lo6oJR9DM2f2fj07UFXqGTpXjS80ULbCrK3HHbDFmph9aoFQDlEGyIuTfwZ32cQpuJbezxeDMdoYq4Aq37qxcQXxh2fVZIJ6LmknRQYkrcBbKXDsX5sUtePnKsx6ImjO2WUOkBHUKhXMwmKjuxY5OOSY1rXnI88YMQMQZYJCAPIY4pUekeU0PmWwziGXb1ZX4NUW8s54f3ZpY34QIumJ5FPVW3LKm73zEgaDvFySBYzqGUdiYhe7JUeA57CgG7E7sb1QWs/fnng9w++ERNwyqG+KUp+GMPEF9yRK6+AZ4ZgmFPhFX5ydRSlxzJKXoUP7myCLOEEG279pGyMAE981InnkClYcCrWm4lotbmHC0ViTEJ+U+gli9ESeviJDxFJBMjNGEC90jhFH9k52qN+/WnSMVqkt7AoOHqUidTws7Rey99ASWROzk/OP5zgsgVh/BfOamXbpoBSRP/5Wj46x6mg="
