layers = {
    "SDE-yitao-32": ["preprocess", '0_11', '1_11', '2_11', 'add_1', 'add_2'],
    "SDE-yitao-32-cifar100": ["preprocess", '0_11', '1_11', '2_11', 'add_1', 'add_2'],
    "SDE-yitao-224": ["preprocess", '0_11', '1_11', '2_11', 'add_1', 'add_2'],
    "ViT-B-16": [f"encoder.layers.encoder_layer_{i}" for i in range(6, 12)],
    "ViT-L-16": [f"encoder.layers.encoder_layer_{i}" for i in range(11, 24, 2)],
    "ViT-L-32": [f"encoder.layers.encoder_layer_{i}" for i in range(11, 24, 2)],
    # "ViT-H-14": [f"encoder.layers.encoder_layer_{i}" for i in range(1, 32, 2)],
    "ViT-H-14": [f"encoder.layers.encoder_layer_{i}" for i in range(21, 32, 2)],
    "alexnet": ["features.12"],
    "alexnet-cifar10": ["features.10", "features.11", "features.12"],
    "alexnet-cifar100": ["features.10", "features.11", "features.12"],
    "cornet-cifar100": ["IT.output"],
    "cornet-cifar10": ["IT.output"],
    "CLIP": [f"encoder.layers.{i}" for i in range(7, 12, 2)],
    "DINO": [f'encoder.layer.{i}' for i in range(7, 12, 2)],
    "DINO": [f'encoder.layer.{i}' for i in range(7, 12, 2)],
    "VIT_B_16_224": [f'blocks.{i}' for i in range(6, 12)],
    "VIT_B_16_224_TOME0": [f'blocks.{i}' for i in range(6, 12)],
    "VIT_B_16_224_TOME_random": [f'blocks.{i}' for i in range(6, 12)],
    "VIT_B_16_224_TOME_linear": [f'blocks.{i}' for i in range(6, 12)],
    "VIT_B_16_224_TOME_linear_1": [f'blocks.{i}' for i in range(6, 12)],
    "deit_small_patch16_224": [f'blocks.{i}' for i in range(6, 12)],
    "swin_tiny_self_trained_cifar10": ['layers.0.blocks.1', 'layers.1.blocks.1', 'layers.1.blocks.3', 'layers.1.blocks.5', 'layers.2.blocks.1'],
    "swin_small_self_trained_cifar10": ['layers.0.blocks.1', 'layers.2.blocks.11', 'layers.2.blocks.13', 'layers.2.blocks.15', 'layers.2.blocks.17', 'layers.3.blocks.1'],
    "vit_tiny_self_trained_cifar10": [f'blocks.{i}' for i in range(4, 8)],
    "vit_small_self_trained_cifar10": [f'blocks.{i}' for i in range(4, 8)],
    "swin_tiny_self_trained_imagenet100": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1',
                                           'layers.2.blocks.0', 'layers.2.blocks.1', 'layers.2.blocks.2', 'layers.2.blocks.3', 'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swin_small_self_trained_imagenet": ['layers.0.blocks.1', 'layers.1.blocks.1', 'layers.2.blocks.1', 'layers.2.blocks.3', 'layers.2.blocks.5', 'layers.2.blocks.7', 'layers.2.blocks.9', 'layers.2.blocks.11', 'layers.2.blocks.13', 'layers.2.blocks.15', 'layers.2.blocks.17', 'layers.3.blocks.1'],
    "swin_base_self_trained_imagenet100": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swin_small_self_trained_imagenet100": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swin_base_self_trained_imagenet": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swin_base_nca_version_self_trained_imagenet": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1',
                                           'layer1.nca_0.0','layer1.nca_0.1',
                                           'layer2.nca_0.0','layer2.nca_0.1','layer2.nca_0.2','layer2.nca_0.3',
                                           'layer3.nca_0.0','layer3.nca_0.1','layer3.nca_0.2'],
    "swin_small_patch4_window7_224": ['layers.1.blocks.0', 'layers.1.blocks.1', 'layers.2.blocks.0', 'layers.2.blocks.1', 'layers.2.blocks.2', 'layers.2.blocks.3', 'layers.2.blocks.4', 'layers.2.blocks.5', 'layers.2.blocks.6', 'layers.2.blocks.7', 'layers.2.blocks.9', 'layers.2.blocks.11', 'layers.2.blocks.12', 'layers.2.blocks.13', 'layers.2.blocks.14', 'layers.2.blocks.15','layers.2.blocks.16', 'layers.2.blocks.17', 'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swin_base_patch4_window7_224": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "swinv2_base": ['layers.0.blocks.0', 'layers.0.blocks.1', 'layers.1.blocks.0', 'layers.1.blocks.1', 
                                           'layers.2.blocks.0', 'layers.2.blocks.1',
                                           'layers.2.blocks.2', 'layers.2.blocks.3',
                                           'layers.2.blocks.4', 'layers.2.blocks.5',
                                           'layers.2.blocks.6', 'layers.2.blocks.7',
                                           'layers.2.blocks.8', 'layers.2.blocks.9',
                                           'layers.2.blocks.10', 'layers.2.blocks.11',
                                           'layers.2.blocks.12', 'layers.2.blocks.13',
                                           'layers.2.blocks.14', 'layers.2.blocks.15',
                                           'layers.2.blocks.16', 'layers.2.blocks.17',
                                           'layers.3.blocks.0', 'layers.3.blocks.1'],
    "convit_base":['blocks.0', 'blocks.1',
                                           'blocks.2', 'blocks.3',
                                           'blocks.4', 'blocks.5',
                                           'blocks.6', 'blocks.7',
                                           'blocks.8', 'blocks.9',
                                           'blocks.10', 'blocks.11'],
    "convit_base_nca_version_self_trained_imagenet":['blocks.0', 'blocks.1',
                                           'blocks.2', 'blocks.3',
                                           'blocks.4', 'blocks.5',
                                           'blocks.6', 'blocks.7',
                                           'blocks.8', 'blocks.9',
                                           'blocks.10', 'blocks.11',
                                           'nca_0.0', 'nca_0.1', 'nca_0.2', 'nca_0.3', 
                                           'nca_1.0', 'nca_1.1', 'nca_1.2', ],
    "rvt_base_plus":['transformers.0.blocks.0', 'transformers.0.blocks.1',
                                           'transformers.0.blocks.2', 'transformers.0.blocks.3',
                                           'transformers.0.blocks.4', 'transformers.0.blocks.5',
                                           'transformers.0.blocks.6', 'transformers.0.blocks.7',
                                           'transformers.0.blocks.8', 'transformers.0.blocks.9',
                                           'transformers.0.blocks.10', 'transformers.0.blocks.11'],
    "rvt_base_plus_nca_version_self_trained_imagenet":['transformers.0.blocks.0', 'transformers.0.blocks.1',
                                           'transformers.0.blocks.2', 'transformers.0.blocks.3',
                                           'transformers.0.blocks.4', 'transformers.0.blocks.5',
                                           'transformers.0.blocks.6', 'transformers.0.blocks.7',
                                           'transformers.0.blocks.8', 'transformers.0.blocks.9',
                                           'transformers.0.blocks.10', 'transformers.0.blocks.11', 
                                           'nca_0.0', 'nca_0.1', 'nca_0.2', 
                                           'nca_1.0', 'nca_1.1', 'nca_1.2', 'nca_1.3',],
    "fan_base_hybrid":['patch_embed.backbone.stages.0','patch_embed.backbone.stages.1','blocks.0', 'blocks.1',
                                           'blocks.2', 'blocks.3',
                                           'blocks.4', 'blocks.5',
                                           'blocks.6', 'blocks.7',
                                           'blocks.8', 'blocks.9',
                                           'blocks.10', 'blocks.11',
                                           'blocks.12', 'blocks.13',
                                           'blocks.14', 'blocks.15', 'cls_attn_blocks.0', 'cls_attn_blocks.1'],
    "fan_base_hybrid_nca_version_self_trained_imagenet":['patch_embed.backbone.stages.0','patch_embed.backbone.stages.1','blocks.0', 'blocks.1',
                                           'blocks.2', 'blocks.3',
                                           'blocks.4', 'blocks.5',
                                           'blocks.6', 'blocks.7',
                                           'blocks.8', 'blocks.9',
                                           'blocks.10', 'blocks.11',
                                           'blocks.12', 'blocks.13',
                                           'blocks.14', 'blocks.15', 'cls_attn_blocks.0', 'cls_attn_blocks.1',
                                           'nca_0.0', 'nca_0.1',
                                           'nca_1.0', 'nca_1.1', 'nca_1.2', 'nca_1.3',
                                           'nca_2.0', 'nca_2.1', 'nca_2.2', ],
    "swin_base_patch4_window12_384": ['layers.2.blocks.4', 'layers.2.blocks.5', 'layers.2.blocks.6', 'layers.2.blocks.7', 'layers.2.blocks.9', 'layers.2.blocks.10', 'layers.2.blocks.11'], # , 'layers.2.blocks.12', 'layers.2.blocks.13', 'layers.2.blocks.14', 'layers.2.blocks.15','layers.2.blocks.16', 'layers.2.blocks.17', 'layers.3.blocks.0', 'layers.3.blocks.1'
    "swin_tiny_patch4_window7_224": ['layers.2.blocks.2', 'layers.2.blocks.3', 'layers.2.blocks.4', 'layers.2.blocks.5', 'layers.3.blocks.0', 'layers.3.blocks.1'],
    "vit_tiny_self_trained_imagenet": [f'blocks.{i}' for i in range(8, 12)],
    "vit_small_self_trained_imagenet": [f'blocks.{i}' for i in range(8, 12)],
    "nca_vit_self_trained_wtalivemask_cifar10": [   'block_nca.1',
                                                    'block.1',
                                                    'block_merge.1',
                                                    'block_nca_middle.1.2',
                                                    'block_nca_middle.1.3',
                                                    'block_nca_middle.1.4',],
    "nca_vit_self_trained_noalivemask_cifar10": [   'block_nca.1',
                                                    'block.1',
                                                    'block_merge.1',
                                                    'block_nca_middle.1.2',
                                                    'block_nca_middle.1.3',
                                                    'block_nca_middle.1.4',],
    "nca_vit_self_trained_wtalivemask_imagenet100": [
                                                    'block_nca.0',
                                                    'block.0',
                                                    'block_nca_middle.0.0',
                                                    'block_nca_middle.0.1',
                                                    'block_nca_middle.0.2',
                                                    'block_merge.0',
                                                    'block_nca.1',
                                                    'block.1',
                                                    'block_nca_middle.1.0',
                                                    'block_nca_middle.1.1',
                                                    'block_nca_middle.1.2',
                                                    'block_merge.1',
                                                    'block_nca.2',
                                                    'block.2',
                                                    'block_nca_middle.2.0',
                                                    'block_nca_middle.2.1',
                                                    'block_nca_middle.2.2',
                                                    'block_nca_middle.2.3',
                                                    'block_nca_middle.2.4',
                                                    'block_nca_middle.2.5',
                                                    'block_merge.2',
                                                    'block_nca.3',
                                                    'block.3',
                                                    'block_nca_middle.3.0',
                                                    'block_nca_middle.3.1',
                                                    'block_nca_middle.3.2',
                                                    'block_nca_middle.3.3',
                                                    'block_nca_middle.3.4',
                                                    'block_nca_middle.3.5',
                                                    'block_merge.3',],
    "nca_vit_self_trained_noalivemask_imagenet100": [
                                                    'block_nca.0',
                                                    'block.0',
                                                    'block_nca_middle.0.0',
                                                    'block_nca_middle.0.1',
                                                    'block_nca_middle.0.2',
                                                    'block_merge.0',
                                                    'block_nca.1',
                                                    'block.1',
                                                    'block_nca_middle.1.0',
                                                    'block_nca_middle.1.1',
                                                    'block_nca_middle.1.2',
                                                    'block_merge.1',
                                                    'block_nca.2',
                                                    'block.2',
                                                    'block_nca_middle.2.0',
                                                    'block_nca_middle.2.1',
                                                    'block_nca_middle.2.2',
                                                    'block_nca_middle.2.3',
                                                    'block_merge.2',
                                                    'block_nca.3',
                                                    'block.3',
                                                    'block_nca_middle.3.0',
                                                    'block_nca_middle.3.1',
                                                    'block_nca_middle.3.2',
                                                    'block_nca_middle.3.3',
                                                    'block_merge.3',],
    "nca_vit_self_trained_wtalivemask_imagenet100_vone": [
                                                    'frontend',
                                                    'frontend_down',
                                                    'block_nca.0',
                                                    'block.0',
                                                    'block_attn.0',
                                                    'block_nca_middle.0.0',
                                                    'block_nca_middle.0.1',
                                                    'block_nca_middle.0.2',
                                                    'block_merge.0',
                                                    'block_nca.1',
                                                    'block.1',
                                                    'block_attn.1',
                                                    'block_nca_middle.1.0',
                                                    'block_nca_middle.1.1',
                                                    'block_nca_middle.1.2',
                                                    'block_merge.1',
                                                    'block_nca.2',
                                                    'block.2',
                                                    'block_attn.2',
                                                    'block_nca_middle.2.0',
                                                    'block_nca_middle.2.1',
                                                    'block_nca_middle.2.2',
                                                    'block_nca_middle.2.3',
                                                    'block_merge.2',
                                                    'block_nca.3',
                                                    'block.3',
                                                    'block_attn.3',
                                                    'block_nca_middle.3.0',
                                                    'block_nca_middle.3.1',
                                                    'block_nca_middle.3.2',
                                                    'block_nca_middle.3.3',
                                                    'block_merge.3',],
    "resnet18_cifar10": [f'layer{i}' for i in range(1, 5)],
    
    "rvt_small_plus": [f'transformers.0.blocks.{i}' for i in range(12)],
}
# 'block_nca.0',
# 'block.0',
# 'block_nca_middle.0.0',
# 'block_nca_middle.0.1',
# 'block_nca_middle.0.2',
# 'block_nca_middle.0.3',
# 'block_nca_middle.0.4',
# 'block_nca_middle.0.5',
# 'block_merge.0',
# 'block_nca.1',
# 'block.1',
# 'block_nca_middle.1.0',
# 'block_nca_middle.1.1',
# 'block_nca_middle.1.2',
# 'block_nca_middle.1.3',
# 'block_nca_middle.1.4',
# 'block_merge.1',
# 'block_nca.2',
# 'block.2',
# 'block_nca_middle.2.0',
# 'block_nca_middle.2.1',
# 'block_nca_middle.2.2',
# 'block_nca_middle.2.3',
# 'block_merge.2'
for r in range(1, 17):
    layers[f"VIT_B_16_224_TOME{r}"] = [f'blocks.{i}' for i in range(6, 12)]