name: brainscore
channels:
- defaults
dependencies:
- xarray
- numpy
- pandas
- six
- requests
- boto3
- tqdm
- netcdf4
- scipy
- scikit-learn
- networkx
- pytest
- Pillow
- jupyter
- matplotlib
- pip:
  - pathos
  - peewee
  - git+https://github.com/mschrimpf/result_caching
