data:
  channels: 3
  color_jitter: 0.0
  dataset: UCF101
  gaussian_dequantization: false
  image_size: 64
  logit_transform: false
  num_frames: 1
  num_frames_cond: 12
  num_frames_future: 0
  num_workers: 4
  prob_mask_cond: 0.0
  prob_mask_future: 0.0
  prob_mask_sync: false
  random_flip: true
  rescaled: true
  uniform_dequantization: false
fast_fid:
  batch_size: 1000
  begin_ckpt: 5000
  end_ckpt: 300000
  ensemble: false
  freq: 5000
  n_steps_each: 0
  num_samples: 1000
  pr_nn_k: 3
  step_lr: 0.0
  verbose: false
model:
  arch: unetmore
  attn_resolutions:
  - 8
  - 16
  - 32
  ch_mult:
  - 1
  - 2
  - 3
  - 4
  cond_emb: false
  conditional: true
  depth: deeper
  dropout: 0.1
  ema: true
  ema_rate: 0.999
  gamma: false
  n_head_channels: 96
  ngf: 192
  noise_in_cond: false
  nonlinearity: swish
  normalization: InstanceNorm++
  num_classes: 1000
  num_res_blocks: 2
  output_all_frames: false
  sigma_begin: 0.02
  sigma_dist: linear
  sigma_end: 0.0001
  spade: false
  spade_dim: 128
  spec_norm: false
  time_conditional: true
  type: v1
  version: DDPM
optim:
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0001
  optimizer: Adam
  warmup: 5000
  weight_decay: 0.0
sampling:
  batch_size: 100
  ckpt_id: 0
  clip_before: true
  consistent: true
  data_init: false
  denoise: true
  fid: false
  final_only: true
  fvd: false
  init_prev_t: -1.0
  inpainting: false
  interpolation: false
  max_data_iter: 100000
  n_interpolations: 15
  n_steps_each: 0
  num_frames_pred: 28
  num_samples4fid: 10000
  num_samples4fvd: 10000
  one_frame_at_a_time: false
  preds_per_test: 1
  ssim: true
  step_lr: 0.0
  subsample: 100
  train: false
test:
  batch_size: 100
  begin_ckpt: 5000
  end_ckpt: 300000
training:
  L1: false
  batch_size: 64
  log_all_sigmas: false
  log_freq: 100
  n_epochs: 1000000
  n_iters: 3000001
  sample_freq: 50000
  snapshot_freq: 50000
  snapshot_sampling: true
  val_freq: 5000
