-- Proposal only. This file has not been applied to any database.
-- It replaces the flat brainscore_modelmeta shape with a canonical model
-- entity, immutable metadata documents, and a typed relational projection.

CREATE SCHEMA IF NOT EXISTS model_metadata_v2;

CREATE TABLE model_metadata_v2.model_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain text NOT NULL,
    identifier text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (domain, identifier),
    CHECK (domain IN ('vision', 'language'))
);

-- One canonical registry model can be associated with one or more historical
-- rows in the existing leaderboard model table without duplicating metadata.
CREATE TABLE model_metadata_v2.model_binding (
    model_id integer PRIMARY KEY
        REFERENCES public.brainscore_model(id) ON DELETE CASCADE,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE
);

CREATE INDEX model_binding_entity_idx
    ON model_metadata_v2.model_binding (entity_id);

-- The validated YAML document is immutable and retained losslessly. Typed
-- tables below are a replaceable projection of the current document.
CREATE TABLE model_metadata_v2.metadata_document (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    schema_version text NOT NULL,
    schema_url text NOT NULL,
    payload jsonb NOT NULL,
    content_sha256 character(64) NOT NULL,
    source_path text NOT NULL,
    source_revision text,
    imported_at timestamptz NOT NULL DEFAULT now(),
    is_current boolean NOT NULL DEFAULT false,
    UNIQUE (id, entity_id),
    UNIQUE (entity_id, content_sha256),
    CHECK (schema_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),
    CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE UNIQUE INDEX metadata_document_one_current_idx
    ON model_metadata_v2.metadata_document (entity_id)
    WHERE is_current;

CREATE INDEX metadata_document_payload_gin_idx
    ON model_metadata_v2.metadata_document USING gin (payload jsonb_path_ops);

-- Fields used by filters, sorting, comparisons, and the model-card header are
-- typed here. Long-form and less frequently queried data stays in the document
-- or in the focused child tables below.
CREATE TABLE model_metadata_v2.model_profile (
    entity_id bigint PRIMARY KEY
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    document_id bigint NOT NULL UNIQUE,
    display_name text NOT NULL,
    model_version text,
    architecture_family text,
    architecture_description text,
    parameter_count bigint,
    parameter_count_is_estimate boolean,
    trainable_layer_count integer,
    trainable_layer_description text,
    recurrent boolean,
    input_modality text NOT NULL DEFAULT 'image',
    input_channels smallint,
    input_height integer,
    input_width integer,
    visual_degrees numeric(7, 3),
    visual_degrees_description text,
    supervision_type text,
    curation_confidence text,
    tokenizer_present boolean,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (architecture_family IN (
        'convolutional_neural_network',
        'vision_transformer',
        'recurrent_convolutional_neural_network',
        'hybrid_convolutional_transformer',
        'hybrid_biological_convolutional',
        'raw_pixels',
        'other'
    )),
    CHECK (parameter_count IS NULL OR parameter_count >= 0),
    CHECK (parameter_count IS NOT NULL OR parameter_count_is_estimate IS NULL),
    CHECK (trainable_layer_count IS NULL OR trainable_layer_count >= 0),
    CHECK (input_channels IS NULL OR input_channels > 0),
    CHECK (input_height IS NULL OR input_height > 0),
    CHECK (input_width IS NULL OR input_width > 0),
    CHECK (visual_degrees IS NULL OR visual_degrees > 0),
    CHECK (curation_confidence IS NULL OR curation_confidence IN (
        'low', 'medium', 'medium_high', 'high'
    )),
    CHECK (supervision_type IS NULL OR supervision_type IN (
        'supervised',
        'self_supervised',
        'weakly_supervised',
        'unsupervised',
        'mixed',
        'other'
    )),
    FOREIGN KEY (document_id, entity_id)
        REFERENCES model_metadata_v2.metadata_document(id, entity_id)
        ON DELETE CASCADE
);

CREATE INDEX model_profile_architecture_idx
    ON model_metadata_v2.model_profile (architecture_family);

CREATE INDEX model_profile_parameter_count_idx
    ON model_metadata_v2.model_profile (parameter_count);

CREATE INDEX model_profile_input_size_idx
    ON model_metadata_v2.model_profile (input_height, input_width);

CREATE INDEX model_profile_supervision_idx
    ON model_metadata_v2.model_profile (supervision_type);

CREATE TABLE model_metadata_v2.preprocessing (
    entity_id bigint PRIMARY KEY
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    resize_height integer,
    resize_width integer,
    crop_height integer,
    crop_width integer,
    interpolation text,
    normalization_mean double precision[],
    normalization_standard_deviation double precision[],
    implementation text,
    description text,
    configuration jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (resize_height IS NULL OR resize_height > 0),
    CHECK (resize_width IS NULL OR resize_width > 0),
    CHECK (crop_height IS NULL OR crop_height > 0),
    CHECK (crop_width IS NULL OR crop_width > 0),
    CHECK (interpolation IS NULL OR interpolation IN (
        'nearest', 'bilinear', 'bicubic', 'lanczos', 'area', 'other'
    )),
    CHECK (
        normalization_mean IS NULL
        OR cardinality(normalization_mean) > 0
    ),
    CHECK (
        normalization_standard_deviation IS NULL
        OR cardinality(normalization_standard_deviation) > 0
    ),
    CHECK (jsonb_typeof(configuration) = 'object')
);

CREATE TABLE model_metadata_v2.dataset (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier text NOT NULL UNIQUE,
    display_name text NOT NULL,
    description text
);

CREATE TABLE model_metadata_v2.training_stage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    stage_order smallint NOT NULL,
    stage_type text NOT NULL,
    description text,
    objective_description text,
    loss_description text,
    learning_rate numeric,
    batch_size bigint,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (entity_id, stage_order),
    UNIQUE (id, entity_id),
    CHECK (stage_order > 0),
    CHECK (stage_type IN (
        'pretraining', 'fine_tuning', 'distillation', 'adaptation', 'other'
    )),
    CHECK (learning_rate IS NULL OR learning_rate >= 0),
    CHECK (batch_size IS NULL OR batch_size > 0),
    CHECK (jsonb_typeof(details) = 'object')
);

CREATE TABLE model_metadata_v2.model_dataset_usage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    dataset_id bigint NOT NULL
        REFERENCES model_metadata_v2.dataset(id) ON DELETE RESTRICT,
    training_stage_id bigint,
    role text NOT NULL,
    sample_count bigint,
    sample_unit text,
    description text,
    FOREIGN KEY (training_stage_id, entity_id)
        REFERENCES model_metadata_v2.training_stage(id, entity_id)
        ON DELETE CASCADE,
    CHECK (role IN (
        'training', 'pretraining', 'fine_tuning', 'validation', 'testing'
    )),
    CHECK (sample_count IS NULL OR sample_count >= 0),
    CHECK (sample_unit IS NULL OR sample_unit IN (
        'images', 'image_text_pairs', 'videos', 'tokens', 'examples', 'other'
    ))
);

CREATE INDEX model_dataset_usage_entity_idx
    ON model_metadata_v2.model_dataset_usage (entity_id, role);

CREATE INDEX model_dataset_usage_dataset_idx
    ON model_metadata_v2.model_dataset_usage (dataset_id, role);

CREATE TABLE model_metadata_v2.artifact (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    role text NOT NULL,
    provider text,
    identifier text,
    url text,
    repository_path text,
    sha256 character(64),
    license_expression text,
    ordinal smallint NOT NULL DEFAULT 0,
    CHECK (role IN (
        'weights', 'source_code', 'configuration', 'tokenizer', 'other'
    )),
    CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'),
    CHECK (ordinal >= 0)
);

CREATE INDEX artifact_entity_role_idx
    ON model_metadata_v2.artifact (entity_id, role);

CREATE TABLE model_metadata_v2.model_relationship (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    target_entity_id bigint
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE RESTRICT,
    external_identifier text,
    external_name text,
    relationship_type text NOT NULL,
    description text,
    CHECK (relationship_type IN (
        'derived_from', 'fine_tuned_from', 'variant_of', 'sibling_of'
    )),
    CHECK (
        target_entity_id IS NOT NULL
        OR external_identifier IS NOT NULL
        OR external_name IS NOT NULL
    ),
    CHECK (target_entity_id IS NULL OR target_entity_id <> source_entity_id)
);

CREATE INDEX model_relationship_source_idx
    ON model_metadata_v2.model_relationship (source_entity_id, relationship_type);

CREATE INDEX model_relationship_target_idx
    ON model_metadata_v2.model_relationship (target_entity_id);

CREATE TABLE model_metadata_v2.intended_use_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    category text NOT NULL,
    item_order smallint NOT NULL,
    value text NOT NULL,
    UNIQUE (entity_id, category, item_order),
    CHECK (category IN ('application', 'user', 'limitation', 'bias')),
    CHECK (item_order >= 0),
    CHECK (length(value) > 0)
);

CREATE TABLE model_metadata_v2.party (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_type text NOT NULL,
    name text NOT NULL,
    canonical_url text,
    UNIQUE (party_type, name),
    CHECK (party_type IN ('person', 'organization'))
);

CREATE TABLE model_metadata_v2.contribution (
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    party_id bigint NOT NULL
        REFERENCES model_metadata_v2.party(id) ON DELETE RESTRICT,
    role text NOT NULL DEFAULT 'creator',
    ordinal smallint NOT NULL DEFAULT 0,
    PRIMARY KEY (entity_id, party_id, role),
    CHECK (role IN (
        'creator', 'maintainer', 'weights_provider', 'checkpoint_host', 'other'
    )),
    CHECK (ordinal >= 0)
);

CREATE TABLE model_metadata_v2.reference (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL UNIQUE,
    title text,
    doi text,
    citation text
);

CREATE TABLE model_metadata_v2.model_reference (
    entity_id bigint NOT NULL
        REFERENCES model_metadata_v2.model_entity(id) ON DELETE CASCADE,
    reference_id bigint NOT NULL
        REFERENCES model_metadata_v2.reference(id) ON DELETE RESTRICT,
    role text NOT NULL,
    PRIMARY KEY (entity_id, reference_id, role),
    CHECK (role IN (
        'primary', 'architecture', 'training', 'weights', 'dataset', 'other'
    ))
);

CREATE TABLE model_metadata_v2.provenance_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL
        REFERENCES model_metadata_v2.metadata_document(id) ON DELETE CASCADE,
    source_key text NOT NULL,
    source_type text NOT NULL,
    title text,
    url text,
    repository_path text,
    revision text,
    UNIQUE (document_id, source_key),
    UNIQUE (id, document_id),
    CHECK (source_type IN (
        'curation',
        'source_code',
        'checkpoint',
        'paper',
        'dataset',
        'model_card',
        'other'
    ))
);

CREATE TABLE model_metadata_v2.assertion (
    document_id bigint NOT NULL
        REFERENCES model_metadata_v2.metadata_document(id) ON DELETE CASCADE,
    json_pointer text NOT NULL,
    verification_status text NOT NULL,
    source_id bigint NOT NULL,
    note text,
    PRIMARY KEY (document_id, json_pointer),
    FOREIGN KEY (source_id, document_id)
        REFERENCES model_metadata_v2.provenance_source(id, document_id)
        ON DELETE CASCADE,
    CHECK (json_pointer LIKE '/%'),
    CHECK (verification_status IN (
        'verified', 'inferred', 'undocumented'
    ))
);

CREATE INDEX assertion_status_idx
    ON model_metadata_v2.assertion (verification_status, document_id);

-- Directly supports the provenance card shown in the proposed model page.
CREATE VIEW model_metadata_v2.verification_summary AS
SELECT
    document.entity_id,
    count(*) FILTER (
        WHERE assertion.verification_status = 'verified'
    ) AS verified_count,
    count(*) FILTER (
        WHERE assertion.verification_status = 'inferred'
    ) AS inferred_count,
    count(*) FILTER (
        WHERE assertion.verification_status = 'undocumented'
    ) AS undocumented_count,
    count(*) AS assertion_count
FROM model_metadata_v2.metadata_document AS document
JOIN model_metadata_v2.assertion AS assertion
    ON assertion.document_id = document.id
WHERE document.is_current
GROUP BY document.entity_id;

-- Import contract:
-- 1. Validate metadata.yml against model-metadata-v2.schema.json.
-- 2. Begin one transaction and lock the model_entity row.
-- 3. Insert the immutable metadata_document and mark the previous document
--    non-current.
-- 4. Replace the entity's typed projection and child rows.
-- 5. Mark the new document current and commit.
-- The database is a query projection; metadata.yml remains the source of truth.
