import os

# Set direct paths for the system being used 
MODEL_BASE_PATH = os.path.dirname(os.path.abspath(__file__))
VISION_TURK_WEB_PATH = 'https://mcdermottlab.mit.edu/mturk_stimuli/imagerec_robust_models_v1/'
AUDIO_TURK_WEB_PATH = 'https://mcdermottlab.mit.edu/mturk_stimuli/audio_word_rec_metamers/'
from analysis_scripts.default_paths import IMAGENET_PATH, JSIN_PATH
# Experiment groupings
# Run all experiments out of the same www folder, but have different folders for the image sets

# Note: the experiment numbers here are different than in the paper due to changed naming conventions when
# writing the paper. The paper name is included in "paper_experiment_name". 
TURK_IMAGE_EXPERIMENTS_GROUPINGS = {'experiment_1': {'networks': ['cornet_s', 'alexnet', 'vgg_19', 'resnet50', 'resnet101'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_1_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 1 (Standard Models)'},
                                    'experiment_3': {'networks': ['resnet50', 'resnet50_l2_3_robust', 'resnet50_linf_4_robust', 'resnet50_linf_8_robust', 
                                                                  'resnet50_random_l2_perturb', 'resnet50_random_linf8_perturb'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment3_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment3_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_3_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 4 (ResNet50 Adversarially Robust)'},
                                    'experiment_4': {'networks': ['alexnet', 'alexnet_l2_3_robust', 'alexnet_random_l2_3_perturb',
                                                                  'alexnet_linf_8_robust', 'alexnet_random_linf8_perturb'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment4_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment4_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_4_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 5 (AlexNet Adversarially Robust)'},
                                    'experiment_5': {'networks': ['resnet50', 'resnet50_simclr', 'resnet50_moco_v2', 'resnet50_byol'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment5_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment5_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_5_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 2 (Self-Supervised Models)'},
                                    'experiment_6': {'networks': ['hmax_standard'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment6_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment6_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_6_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 3 (HMAX)'},
                                    'experiment_9': {'networks': ['alexnet_early_checkpoint','alexnet_reduced_aliasing_early_checkpoint', 'vonealexnet_gaussian_noise_std4_fixed'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/imagerec_robust_models_v1/experiment9_images',
                                                     'experiment_folder_web':VISION_TURK_WEB_PATH + 'experiment9_images',
                                                     'experiment_params_web':VISION_TURK_WEB_PATH + 'FOR_WEB_vision_experiment_9_load_experiment_info.json',
                                                     'paper_experiment_name':'Visual Experiment 6 (Lowpass AlexNet and VOneNet)'},
                                   }

TURK_AUDIO_EXPERIMENTS_GROUPINGS = {'experiment_1': {'networks': ['kell2018', 'cochresnet50'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment1_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment1_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_1_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 1 (Standard Models)'},
                                    'experiment_3': {'networks': ['cochresnet50', 'cochresnet50_l2_1_robust_waveform', 'cochresnet50_l2_p5_robust_waveform', 
                                                                  'cochresnet50_linf_p002_robust_waveform', 'cochresnet50_l2_1_random_step_waveform', 
                                                                  'cochresnet50_linf_p002_random_step_waveform'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment3_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment3_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_3_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 3 (CochResNet50 Waveform Adversarial Training)'},
                                    'experiment_4': {'networks': ['kell2018', 'kell2018_l2_1_robust_waveform', 'kell2018_l2_1_random_step_waveform', 
                                                                  'kell2018_linf_p002_robust_waveform', 'kell2018_linf_p002_random_step_waveform'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment4_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment4_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_4_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 4 (CochCNN9 Waveform Adversarial Training)'},
                                    'experiment_6': {'networks': ['spectemp_filters'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment6_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment6_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_6_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 2 (Spectemp Model)'},
                                    'experiment_7': {'networks': ['cochresnet50', 'cochresnet50_l2_1_robust_cochleagram', 'cochresnet50_l2_p5_robust_cochleagram',
                                                                  'cochresnet50_l2_1_random_step_cochleagram', 'cochresnet50_l2_1_robust_waveform'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment7_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment7_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_7_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 5 (CochResNet50 Cochleagram Adversarial Training)'},
                                    'experiment_8': {'networks': ['kell2018', 'kell2018_l2_1_robust_cochleagram', 'kell2018_l2_p5_robust_cochleagram',
                                                                  'kell2018_l2_1_random_step_cochleagram', 'kell2018_l2_1_robust_waveform'],
                                                     'experiment_folder': '/mindhive/mcdermott/www/mturk_stimuli/audio_word_rec_metamers/experiment8_audio',
                                                     'experiment_folder_web':AUDIO_TURK_WEB_PATH + 'experiment8_audio',
                                                     'experiment_params_web':AUDIO_TURK_WEB_PATH + 'FOR_WEB_audio_experiment_8_load_experiment_info.json',
                                                     'paper_experiment_name':'Audio Experiment 6 (CochCNN9 Cochleagram Adversarial Training)'},
                                   }

ALL_NETWORKS_AND_LAYERS_AUDIO = {
    'kell2018':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'layers_fake_relu_comparison': [
                           'input_after_preproc',
                           'relu0',
                           'relu0_fakerelu',
                           'relu1',
                           'relu1_fakerelu',
                           'relu2',
                           'relu2_fakerelu',
                           'relu3',
                           'relu3_fakerelu',
                           'relu4',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 Standard',
    },
    'kell2018_l2_1_robust_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_l2_1_robust_waveform'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n waveform \n  $L_2-norm (\epsilon=1)$',
    },
    'kell2018_l2_1_random_step_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_l2_1_random_step_waveform'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n random waveform \n $L_2-norm (\epsilon=1)$',
    },
    'kell2018_linf_p002_robust_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_linf_p002_robust_waveform'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n waveform \n  $L_\infty-norm (\epsilon=0.002)$',
    },
    'kell2018_linf_p002_random_step_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_linf_p002_random_step_waveform'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n random waveform \n $L_\infty-norm (\epsilon=0.002)$',
    },
    'kell2018_l2_1_robust_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_l2_1_robust_cochleagram'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n cochleagram \n  $L_2-norm (\epsilon=1)$',
    },
    'kell2018_l2_p5_robust_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_l2_p5_robust_cochleagram'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n cochleagram \n  $L_2-norm (\epsilon=0.5)$',
    },
    'kell2018_l2_1_random_step_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'kell2018_l2_1_random_step_cochleagram'),
                'layers': [
                           'input_after_preproc',
                           'relu0_fakerelu',
                           'relu1_fakerelu',
                           'relu2_fakerelu',
                           'relu3_fakerelu',
                           'relu4_fakerelu',
                           'avgpool',
                           'relufc_fakerelu',
                           'final',
                          ],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochCNN9 \n random cochleagram \n  $L_2-norm (\epsilon=1)$',
    },
    'cochresnet50':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'layers_fake_relu_comparison': ['conv1_relu1', 'conv1_relu1_fake_relu',
                                                'layer1', 'layer1_fake_relu',
                                                'layer2', 'layer2_fake_relu',
                                                'layer3', 'layer3_fake_relu',
                                                'layer4', 'layer4_fake_relu'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_50000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 Standard',
    },
    'cochresnet50_l2_1_robust_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_1_robust_waveform'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n waveform \n  $L_2-norm (\epsilon=1)$',
    },
    'cochresnet50_l2_p5_robust_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_p5_robust_waveform'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n waveform \n  $L_2-norm (\epsilon=0.5)$',
    },
    'cochresnet50_linf_p002_robust_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_linf_p002_robust_waveform'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n waveform \n  $L_\infty-norm (\epsilon=0.002)$',
    },
    'cochresnet50_l2_1_random_step_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_1_random_step_waveform'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n random waveform \n  $L_2-norm (\epsilon=1)$',
    },
    'cochresnet50_linf_p002_random_step_waveform':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_linf_p002_random_step_waveform'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n random waveform \n  $L_\infty-norm (\epsilon=0.002)$',
    },
    'cochresnet50_l2_1_robust_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_1_robust_cochleagram'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n cochleagram \n  $L_2-norm (\epsilon=1)$',
    },
    'cochresnet50_l2_p5_robust_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_p5_robust_cochleagram'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n cochleagram \n  $L_2-norm (\epsilon=0.5)$',
    },
    'cochresnet50_l2_1_random_step_cochleagram':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'cochresnet50_l2_1_random_step_cochleagram'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder':'metamers/psychophysics_wsj400_jsintest_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'CochResNet50 \n random cochleagram \n  $L_2-norm (\epsilon=1)$',
    },
    'spectemp_filters':{'location':os.path.join(MODEL_BASE_PATH, 'audio_networks', 'spectemp_filters'),
                'layers':['input_after_preproc',
                          'filtered_signal',
                          'spectempfilter_power',
                          'avgpool',
                          'final'],
                'neural_regression_folder':'regression_results',
                'neural_analysis_string':"voxelwise_regression_b'%s'_randseed3882_zero_center_fmri_activations.pckl",
                'metamer_folder': 'metamers/psychophysics_wsj400_jsintest_coarse_define_spectemp_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_1000_RS_0_SPLIT_*_START_*.pckl',
                'paper_name':'Spectemp',
    },
}

ALL_NETWORKS_AND_LAYERS_IMAGES = {
    'cornet_s':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'cornet_s'),
                'layers': ['input_after_preproc', 
                           'V1_fake_relu', 
                           'V2_fake_relu', 
                           'V4_fake_relu', 
                           'IT_fake_relu', 
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'CORnet-S Standard',
    },
    'alexnet':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'layers_fake_relu_comparison': ['relu0', 'relu0_fake_relu',
                                                'relu1', 'relu1_fake_relu',
                                                'relu2', 'relu2_fake_relu',
                                                'relu3', 'relu3_fake_relu',
                                                'relu4', 'relu4_fake_relu',
                                                'fc0_relu', 'fc0_relu_fake_relu',
                                                'fc1_relu', 'fc1_relu_fake_relu'
                                               ],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet Standard',
    },
    'alexnet_early_checkpoint':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_early_checkpoint'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet (Early Checkpoint)',
    },
    'vgg_19':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'vgg_19'),
                'layers': ['input_after_preproc',
                           'conv_relu_0_1_fake_relu',
                           'conv_relu_1_1_fake_relu',
                           'conv_relu_2_3_fake_relu',
                           'conv_relu_3_3_fake_relu',
                           'conv_relu_4_3_fake_relu',
                           'avgpool',
                           'fc_relu_0_fake_relu',
                           'fc_relu_1_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_50000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'VGG-19 Standard',
    },
    'resnet50':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'layers_fake_relu_comparison': ['conv1_relu1', 'conv1_relu1_fake_relu',
                                                'layer1', 'layer1_fake_relu',
                                                'layer2', 'layer2_fake_relu',
                                                'layer3', 'layer3_fake_relu',
                                                'layer4', 'layer4_fake_relu'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 Standard',
    },
    'resnet101':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet101'),
                 'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                 'neural_regression_folder':None,
                 'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                 'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                 'paper_name':'ResNet101 Standard',
    },
    'alexnet_reduced_aliasing_early_checkpoint':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_reduced_aliasing_early_checkpoint'),
                'layers': ['input_after_preproc',
                           'relu0_fake_relu', # contains the hpool
                           'relu1_fake_relu', # contains the hpool
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'LowpassAlexNet',
    },
    'resnet50_l2_3_robust':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_l2_3_robust'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_50000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 \n $L_2-norm (\epsilon=3)$',
    },
    'resnet50_linf_4_robust':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_linf_4_robust'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 \n $L_\infty-norm (\epsilon=4/255)$',
    },
    'resnet50_linf_8_robust':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_linf_8_robust'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 \n  $L_\infty-norm (\epsilon=8/255)$',
    },
    'resnet50_random_l2_perturb':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_random_l2_perturb'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 random \n $L_2-norm (\epsilon=3)$',
    },
    'resnet50_random_linf8_perturb':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_random_linf8_perturb'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50 random \n $L_\infty-norm (\epsilon=8/255)$',
    },
    'alexnet_l2_3_robust':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_l2_3_robust'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet \n $L_2-norm (\epsilon=3)$',
    },
    'alexnet_random_l2_3_perturb':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_random_l2_3_perturb'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet random \n $L_2-norm (\epsilon=3)$',
    },
    'alexnet_linf_8_robust':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_linf_8_robust'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet \n $L_\infty-norm (\epsilon=8/255)$',
    },
    'alexnet_random_linf8_perturb':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'alexnet_random_linf8_perturb'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'AlexNet random \n $L_\infty-norm (\epsilon=8/255)$',
    },
    'resnet50_simclr':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_simclr'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50-SIMCLR',
    },
    'resnet50_moco_v2':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_moco_v2'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50-MOCO_V2',
    },
    'resnet50_byol':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'resnet50_byol'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_50000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'ResNet50-BYOL',
    },
    'hmax_standard':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'hmax_standard'),
                'layers':[
                          'input_after_preproc',
                          's1_out',
                          'c1_out_no_reshape',
                          's2_out_reshape_to_list',
                          'c2_out',
                          'final',
                          ],
                # Because of the unit dropout, the metmaers were generated with these layers after we constructed null
                'remap_pckl_keys': {'c1_out':'c1_out_no_reshape',
                                    's2_out':'s2_out_reshape_to_list',
                                   },
               
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_random_single_unit_optimization_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_1000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'HMAX',
    },
    'vonealexnet_gaussian_noise_std4_fixed':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'vonealexnet_gaussian_noise_std4_fixed'),
                'layers':['input_after_preproc',
#                           'gabors_f',
                          'v1_output',
#                           'bottleneck',
                          'relu1_fake_relu',
                          'relu2_fake_relu',
                          'relu3_fake_relu',
                          'relu4_fake_relu',
                          'fc0_relu_fake_relu',
                          'fc1_relu_fake_relu',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_10000_RS_*_SPLIT_0_START_0.pckl',
                'paper_name':'VOneAlexNet',
    },
    'texture_shape_alexnet_trained_on_SIN':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'texture_shape_alexnet_trained_on_SIN'),
                'layers': ['input_after_preproc', # Only use the fake_relu layers
                           'relu0_fake_relu',
                           'relu1_fake_relu',
                           'relu2_fake_relu',
                           'relu3_fake_relu',
                           'relu4_fake_relu',
                           'fc0_relu_fake_relu',
                           'fc1_relu_fake_relu',
                           'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'},
    'texture_shape_resnet50_trained_on_SIN':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'texture_shape_resnet50_trained_on_SIN'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'},
    'CLIP_resnet50':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks','CLIP_resnet50'),
                'layers':['input_after_preproc',
                          'stem',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'attnpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'},
    'CLIP_ViT-B_32':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks','CLIP_ViT-B_32'),
                'layers':[# 'input_after_preproc',
         'conv1',
         'class_embedding_cat',
         'ln_pre',
         'block_0',
         'block_3',
         'block_6',
         'block_9',
         'blocks_end',
               #            'final',
                ],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'},
    'vision_transformer_vit_large_patch16_224':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks','vision_transformer_vit_large_patch16_224'),
                'layers':[# 'input_after_preproc',
         'patch_embed',
         'pos_embed',
         'block_0',
         'block_6',
         'block_12',
         'block_18',
         'blocks_end',
                          # 'final'
                ],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'},
    'SWSL_resnet50':{'location':os.path.join(MODEL_BASE_PATH, 'visual_networks', 'SWSL_resnet50'),
                'layers':['input_after_preproc',
                          'conv1_relu1_fake_relu',
                          'layer1_fake_relu',
                          'layer2_fake_relu',
                          'layer3_fake_relu',
                          'layer4_fake_relu',
                          'avgpool',
                          'final'],
                'neural_regression_folder':None,
                'metamer_folder':'metamers/400_16_class_imagenet_val_inversion_loss_layer_RS0_I3000_N8',
                'null_glob':'null_dist/null_dist_N_200000_RS_*_SPLIT_0_START_0.pckl'}
}

