from .resnet import *
from .vgg import *
from .alexnet import *
from .alexnet_reduced_aliasing import * 
from .cornet_s import * 
from .hmax import * 
from .resnet_openselfsup_transfer import * 
from .vonenet import *
from .texture_shape_models import * 
