from brainscore_vision import model_registry
from brainscore_vision.model_helpers.brain_transformation import ModelCommitment
from .model import get_model, get_layers

model_registry['cornet_s_0_0_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_0_0',
    activations_model=get_model('cornet_s_0_0_0'),
    layers=get_layers('cornet_s_0_0_0'))
model_registry['cornet_s_0_0_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_0_4096',
    activations_model=get_model('cornet_s_0_0_4096'),
    layers=get_layers('cornet_s_0_0_4096'))
model_registry['cornet_s_0_10_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_10_0',
    activations_model=get_model('cornet_s_0_10_0'),
    layers=get_layers('cornet_s_0_10_0'))
model_registry['cornet_s_0_10_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_10_4096',
    activations_model=get_model('cornet_s_0_10_4096'),
    layers=get_layers('cornet_s_0_10_4096'))
model_registry['cornet_s_0_11_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_11_0',
    activations_model=get_model('cornet_s_0_11_0'),
    layers=get_layers('cornet_s_0_11_0'))
model_registry['cornet_s_0_12_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_12_0',
    activations_model=get_model('cornet_s_0_12_0'),
    layers=get_layers('cornet_s_0_12_0'))
model_registry['cornet_s_0_12_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_12_4096',
    activations_model=get_model('cornet_s_0_12_4096'),
    layers=get_layers('cornet_s_0_12_4096'))
model_registry['cornet_s_0_13_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_13_0',
    activations_model=get_model('cornet_s_0_13_0'),
    layers=get_layers('cornet_s_0_13_0'))
model_registry['cornet_s_0_14_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_14_0',
    activations_model=get_model('cornet_s_0_14_0'),
    layers=get_layers('cornet_s_0_14_0'))
model_registry['cornet_s_0_14_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_14_4096',
    activations_model=get_model('cornet_s_0_14_4096'),
    layers=get_layers('cornet_s_0_14_4096'))
model_registry['cornet_s_0_15_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_15_0',
    activations_model=get_model('cornet_s_0_15_0'),
    layers=get_layers('cornet_s_0_15_0'))
model_registry['cornet_s_0_16_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_16_4096',
    activations_model=get_model('cornet_s_0_16_4096'),
    layers=get_layers('cornet_s_0_16_4096'))
model_registry['cornet_s_0_18_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_18_4096',
    activations_model=get_model('cornet_s_0_18_4096'),
    layers=get_layers('cornet_s_0_18_4096'))
model_registry['cornet_s_0_1_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_1_0',
    activations_model=get_model('cornet_s_0_1_0'),
    layers=get_layers('cornet_s_0_1_0'))
model_registry['cornet_s_0_20_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_20_4096',
    activations_model=get_model('cornet_s_0_20_4096'),
    layers=get_layers('cornet_s_0_20_4096'))
model_registry['cornet_s_0_22_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_22_4096',
    activations_model=get_model('cornet_s_0_22_4096'),
    layers=get_layers('cornet_s_0_22_4096'))
model_registry['cornet_s_0_24_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_24_4096',
    activations_model=get_model('cornet_s_0_24_4096'),
    layers=get_layers('cornet_s_0_24_4096'))
model_registry['cornet_s_0_26_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_26_4096',
    activations_model=get_model('cornet_s_0_26_4096'),
    layers=get_layers('cornet_s_0_26_4096'))
model_registry['cornet_s_0_28_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_28_4096',
    activations_model=get_model('cornet_s_0_28_4096'),
    layers=get_layers('cornet_s_0_28_4096'))
model_registry['cornet_s_0_2_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_2_0',
    activations_model=get_model('cornet_s_0_2_0'),
    layers=get_layers('cornet_s_0_2_0'))
model_registry['cornet_s_0_2_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_2_4096',
    activations_model=get_model('cornet_s_0_2_4096'),
    layers=get_layers('cornet_s_0_2_4096'))
model_registry['cornet_s_0_3_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_3_0',
    activations_model=get_model('cornet_s_0_3_0'),
    layers=get_layers('cornet_s_0_3_0'))
model_registry['cornet_s_0_4_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_4_0',
    activations_model=get_model('cornet_s_0_4_0'),
    layers=get_layers('cornet_s_0_4_0'))
model_registry['cornet_s_0_4_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_4_4096',
    activations_model=get_model('cornet_s_0_4_4096'),
    layers=get_layers('cornet_s_0_4_4096'))
model_registry['cornet_s_0_5_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_5_0',
    activations_model=get_model('cornet_s_0_5_0'),
    layers=get_layers('cornet_s_0_5_0'))
model_registry['cornet_s_0_6_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_6_0',
    activations_model=get_model('cornet_s_0_6_0'),
    layers=get_layers('cornet_s_0_6_0'))
model_registry['cornet_s_0_6_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_6_4096',
    activations_model=get_model('cornet_s_0_6_4096'),
    layers=get_layers('cornet_s_0_6_4096'))
model_registry['cornet_s_0_7_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_7_0',
    activations_model=get_model('cornet_s_0_7_0'),
    layers=get_layers('cornet_s_0_7_0'))
model_registry['cornet_s_0_8_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_8_0',
    activations_model=get_model('cornet_s_0_8_0'),
    layers=get_layers('cornet_s_0_8_0'))
model_registry['cornet_s_0_8_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_0_8_4096',
    activations_model=get_model('cornet_s_0_8_4096'),
    layers=get_layers('cornet_s_0_8_4096'))
model_registry['cornet_s_0_9_0'] = lambda: ModelCommitment(
    identifier='cornet_s_0_9_0',
    activations_model=get_model('cornet_s_0_9_0'),
    layers=get_layers('cornet_s_0_9_0'))
model_registry['cornet_s_1_0_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_0_0',
    activations_model=get_model('cornet_s_1_0_0'),
    layers=get_layers('cornet_s_1_0_0'))
model_registry['cornet_s_1_10_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_10_0',
    activations_model=get_model('cornet_s_1_10_0'),
    layers=get_layers('cornet_s_1_10_0'))
model_registry['cornet_s_1_10_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_1_10_4096',
    activations_model=get_model('cornet_s_1_10_4096'),
    layers=get_layers('cornet_s_1_10_4096'))
model_registry['cornet_s_1_11_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_11_0',
    activations_model=get_model('cornet_s_1_11_0'),
    layers=get_layers('cornet_s_1_11_0'))
model_registry['cornet_s_1_12_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_12_0',
    activations_model=get_model('cornet_s_1_12_0'),
    layers=get_layers('cornet_s_1_12_0'))
model_registry['cornet_s_1_12_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_1_12_4096',
    activations_model=get_model('cornet_s_1_12_4096'),
    layers=get_layers('cornet_s_1_12_4096'))
model_registry['cornet_s_1_13_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_13_0',
    activations_model=get_model('cornet_s_1_13_0'),
    layers=get_layers('cornet_s_1_13_0'))
model_registry['cornet_s_1_14_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_14_0',
    activations_model=get_model('cornet_s_1_14_0'),
    layers=get_layers('cornet_s_1_14_0'))
model_registry['cornet_s_1_14_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_1_14_4096',
    activations_model=get_model('cornet_s_1_14_4096'),
    layers=get_layers('cornet_s_1_14_4096'))
model_registry['cornet_s_1_15_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_15_0',
    activations_model=get_model('cornet_s_1_15_0'),
    layers=get_layers('cornet_s_1_15_0'))
model_registry['cornet_s_1_16_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_1_16_4096',
    activations_model=get_model('cornet_s_1_16_4096'),
    layers=get_layers('cornet_s_1_16_4096'))
model_registry['cornet_s_1_18_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_1_18_4096',
    activations_model=get_model('cornet_s_1_18_4096'),
    layers=get_layers('cornet_s_1_18_4096'))
model_registry['cornet_s_1_1_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_1_0',
    activations_model=get_model('cornet_s_1_1_0'),
    layers=get_layers('cornet_s_1_1_0'))
model_registry['cornet_s_1_2_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_2_0',
    activations_model=get_model('cornet_s_1_2_0'),
    layers=get_layers('cornet_s_1_2_0'))
model_registry['cornet_s_1_3_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_3_0',
    activations_model=get_model('cornet_s_1_3_0'),
    layers=get_layers('cornet_s_1_3_0'))
model_registry['cornet_s_1_4_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_4_0',
    activations_model=get_model('cornet_s_1_4_0'),
    layers=get_layers('cornet_s_1_4_0'))
model_registry['cornet_s_1_5_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_5_0',
    activations_model=get_model('cornet_s_1_5_0'),
    layers=get_layers('cornet_s_1_5_0'))
model_registry['cornet_s_1_6_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_6_0',
    activations_model=get_model('cornet_s_1_6_0'),
    layers=get_layers('cornet_s_1_6_0'))
model_registry['cornet_s_1_7_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_7_0',
    activations_model=get_model('cornet_s_1_7_0'),
    layers=get_layers('cornet_s_1_7_0'))
model_registry['cornet_s_1_8_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_8_0',
    activations_model=get_model('cornet_s_1_8_0'),
    layers=get_layers('cornet_s_1_8_0'))
model_registry['cornet_s_1_9_0'] = lambda: ModelCommitment(
    identifier='cornet_s_1_9_0',
    activations_model=get_model('cornet_s_1_9_0'),
    layers=get_layers('cornet_s_1_9_0'))
model_registry['cornet_s_2_0_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_0_0',
    activations_model=get_model('cornet_s_2_0_0'),
    layers=get_layers('cornet_s_2_0_0'))
model_registry['cornet_s_2_0_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_0_4096',
    activations_model=get_model('cornet_s_2_0_4096'),
    layers=get_layers('cornet_s_2_0_4096'))
model_registry['cornet_s_2_10_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_10_0',
    activations_model=get_model('cornet_s_2_10_0'),
    layers=get_layers('cornet_s_2_10_0'))
model_registry['cornet_s_2_10_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_10_4096',
    activations_model=get_model('cornet_s_2_10_4096'),
    layers=get_layers('cornet_s_2_10_4096'))
model_registry['cornet_s_2_11_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_11_0',
    activations_model=get_model('cornet_s_2_11_0'),
    layers=get_layers('cornet_s_2_11_0'))
model_registry['cornet_s_2_12_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_12_0',
    activations_model=get_model('cornet_s_2_12_0'),
    layers=get_layers('cornet_s_2_12_0'))
model_registry['cornet_s_2_12_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_12_4096',
    activations_model=get_model('cornet_s_2_12_4096'),
    layers=get_layers('cornet_s_2_12_4096'))
model_registry['cornet_s_2_13_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_13_0',
    activations_model=get_model('cornet_s_2_13_0'),
    layers=get_layers('cornet_s_2_13_0'))
model_registry['cornet_s_2_14_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_14_0',
    activations_model=get_model('cornet_s_2_14_0'),
    layers=get_layers('cornet_s_2_14_0'))
model_registry['cornet_s_2_14_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_14_4096',
    activations_model=get_model('cornet_s_2_14_4096'),
    layers=get_layers('cornet_s_2_14_4096'))
model_registry['cornet_s_2_15_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_15_0',
    activations_model=get_model('cornet_s_2_15_0'),
    layers=get_layers('cornet_s_2_15_0'))
model_registry['cornet_s_2_16_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_16_4096',
    activations_model=get_model('cornet_s_2_16_4096'),
    layers=get_layers('cornet_s_2_16_4096'))
model_registry['cornet_s_2_18_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_18_4096',
    activations_model=get_model('cornet_s_2_18_4096'),
    layers=get_layers('cornet_s_2_18_4096'))
model_registry['cornet_s_2_1_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_1_0',
    activations_model=get_model('cornet_s_2_1_0'),
    layers=get_layers('cornet_s_2_1_0'))
model_registry['cornet_s_2_2_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_2_0',
    activations_model=get_model('cornet_s_2_2_0'),
    layers=get_layers('cornet_s_2_2_0'))
model_registry['cornet_s_2_2_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_2_4096',
    activations_model=get_model('cornet_s_2_2_4096'),
    layers=get_layers('cornet_s_2_2_4096'))
model_registry['cornet_s_2_3_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_3_0',
    activations_model=get_model('cornet_s_2_3_0'),
    layers=get_layers('cornet_s_2_3_0'))
model_registry['cornet_s_2_4_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_4_0',
    activations_model=get_model('cornet_s_2_4_0'),
    layers=get_layers('cornet_s_2_4_0'))
model_registry['cornet_s_2_4_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_4_4096',
    activations_model=get_model('cornet_s_2_4_4096'),
    layers=get_layers('cornet_s_2_4_4096'))
model_registry['cornet_s_2_5_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_5_0',
    activations_model=get_model('cornet_s_2_5_0'),
    layers=get_layers('cornet_s_2_5_0'))
model_registry['cornet_s_2_6_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_6_0',
    activations_model=get_model('cornet_s_2_6_0'),
    layers=get_layers('cornet_s_2_6_0'))
model_registry['cornet_s_2_6_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_6_4096',
    activations_model=get_model('cornet_s_2_6_4096'),
    layers=get_layers('cornet_s_2_6_4096'))
model_registry['cornet_s_2_7_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_7_0',
    activations_model=get_model('cornet_s_2_7_0'),
    layers=get_layers('cornet_s_2_7_0'))
model_registry['cornet_s_2_8_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_8_0',
    activations_model=get_model('cornet_s_2_8_0'),
    layers=get_layers('cornet_s_2_8_0'))
model_registry['cornet_s_2_8_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_2_8_4096',
    activations_model=get_model('cornet_s_2_8_4096'),
    layers=get_layers('cornet_s_2_8_4096'))
model_registry['cornet_s_2_9_0'] = lambda: ModelCommitment(
    identifier='cornet_s_2_9_0',
    activations_model=get_model('cornet_s_2_9_0'),
    layers=get_layers('cornet_s_2_9_0'))
model_registry['cornet_s_3_0_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_0_0',
    activations_model=get_model('cornet_s_3_0_0'),
    layers=get_layers('cornet_s_3_0_0'))
model_registry['cornet_s_3_0_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_0_4096',
    activations_model=get_model('cornet_s_3_0_4096'),
    layers=get_layers('cornet_s_3_0_4096'))
model_registry['cornet_s_3_10_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_10_0',
    activations_model=get_model('cornet_s_3_10_0'),
    layers=get_layers('cornet_s_3_10_0'))
model_registry['cornet_s_3_10_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_10_4096',
    activations_model=get_model('cornet_s_3_10_4096'),
    layers=get_layers('cornet_s_3_10_4096'))
model_registry['cornet_s_3_11_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_11_0',
    activations_model=get_model('cornet_s_3_11_0'),
    layers=get_layers('cornet_s_3_11_0'))
model_registry['cornet_s_3_12_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_12_0',
    activations_model=get_model('cornet_s_3_12_0'),
    layers=get_layers('cornet_s_3_12_0'))
model_registry['cornet_s_3_12_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_12_4096',
    activations_model=get_model('cornet_s_3_12_4096'),
    layers=get_layers('cornet_s_3_12_4096'))
model_registry['cornet_s_3_13_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_13_0',
    activations_model=get_model('cornet_s_3_13_0'),
    layers=get_layers('cornet_s_3_13_0'))
model_registry['cornet_s_3_14_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_14_0',
    activations_model=get_model('cornet_s_3_14_0'),
    layers=get_layers('cornet_s_3_14_0'))
model_registry['cornet_s_3_14_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_14_4096',
    activations_model=get_model('cornet_s_3_14_4096'),
    layers=get_layers('cornet_s_3_14_4096'))
model_registry['cornet_s_3_15_0'] = lambda: ModelCommitment(
    identifier='cornet_s_3_15_0',
    activations_model=get_model('cornet_s_3_15_0'),
    layers=get_layers('cornet_s_3_15_0'))
model_registry['cornet_s_3_16_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_16_4096',
    activations_model=get_model('cornet_s_3_16_4096'),
    layers=get_layers('cornet_s_3_16_4096'))
model_registry['cornet_s_3_18_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_18_4096',
    activations_model=get_model('cornet_s_3_18_4096'),
    layers=get_layers('cornet_s_3_18_4096'))
model_registry['cornet_s_3_20_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_20_4096',
    activations_model=get_model('cornet_s_3_20_4096'),
    layers=get_layers('cornet_s_3_20_4096'))
model_registry['cornet_s_3_22_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_22_4096',
    activations_model=get_model('cornet_s_3_22_4096'),
    layers=get_layers('cornet_s_3_22_4096'))
model_registry['cornet_s_3_24_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_24_4096',
    activations_model=get_model('cornet_s_3_24_4096'),
    layers=get_layers('cornet_s_3_24_4096'))
model_registry['cornet_s_3_26_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_26_4096',
    activations_model=get_model('cornet_s_3_26_4096'),
    layers=get_layers('cornet_s_3_26_4096'))
model_registry['cornet_s_3_28_4096'] = lambda: ModelCommitment(
    identifier='cornet_s_3_28_4096',
    activations_model=get_model('cornet_s_3_28_4096'),
    layers=get_layers('cornet_s_3_28_4096'))
