from brainscore_vision import model_registry
from brainscore_vision.model_helpers import ModelCommitment
from .model import get_model, get_layers

model_registry['effnetb2_cutmixpatch_robust35_avgee5e3_manylayers_424x377'] = ModelCommitment(identifier='effnetb2_cutmixpatch_robust35_avgee5e3_manylayers_424x377', activations_model=get_model('effnetb2_cutmixpatch_robust35_avgee5e3_manylayers_424x377'), layers=get_layers('effnetb2_cutmixpatch_robust35_avgee5e3_manylayers_424x377'))
